# Generated by Django 4.0.3 on 2022-03-17 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('tag', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('thumbnail', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('sub_title', models.CharField(max_length=100)),
                ('sub_desc', models.TextField(max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.tag')),
            ],
        ),
    ]
