# Generated by Django 4.0.3 on 2022-03-18 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_project_tag_project_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('skill', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='projects', to='webapp.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tagname', to='webapp.tag'),
        ),
    ]
