# Generated by Django 4.0.3 on 2022-03-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_skill_project_skill_alter_project_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='projects', to='webapp.skill'),
        ),
    ]
