# Generated by Django 4.0.3 on 2022-03-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_project_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sub_desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_title',
        ),
    ]
